### ISSUE TITLE
Tutorial - widget page is blank with console error

### ISSUE THREAD

**Issue by tyler36** [evercode1/foundation-maker#1]
## Detailed description
Not sure if I missed something somewhere but following the tutorial, I hit a snag trying to view the '/widget' page; it simply displays an empty table.

When I checked the console, I found the following error:
```
QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1 no such function: DATE_FORMAT (SQL: select "id" as "Id", "name" as "Name", DATE_FORMAT(created_at,
"%m-%d-%Y") as Created from "widgets" order by "id" asc limit 10 offset 0)
```

## Context
I'm able to a DD from the WidgetController@index and see 30 widgets so I assume the database is setup correctly.

## Your environment
OS: Win10
PHP: 7.0.8
DB: Sqlite

**Comment by evercode1** [comment]
I haven't tested with Sqlite.  It looks like it is not able to recognize the DATE_FORMAT function, which formats the results. The error it is reporting shows a scrambled query.   It is tested and working with MySql.  I will make it more clear in the docs with my next update that this intended for MySql.  If you have this problem with MySql, reopen and I will take a closer look at it, thanks.

**Comment by tyler36** [comment]
Thank you for the reply
